api:
   IP1: charter.orbiwise.com
   IP2: staging.lorawan.spectrum.net:8443
   IP: staging.lorawan.spectrum.net
   userid: range_test_lora
   password: Charter1234!
   DEV1: '4768C40A0043002C'
   DEV: 474ABD91001C002C


Login:
   user: 
   password: Charter123

Device:
   port: COM6
